# Copyright (c) 2025-2026 Buf Technologies, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated from local_dep/dep.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.1.1 with parameter "".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile


_DepFields: TypeAlias = Literal["value"]

class Dep(Message[_DepFields]):
    """
    ```proto
    message local_dep.Dep
    ```

    Attributes:
        value:
            ```proto
            string value = 1;
            ```
    """

    __slots__ = ("value",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            value: str = "",
        ) -> None:
            pass

        value: str


_DESC = file_desc(
    b'\n\x13local_dep/dep.proto\x12\tlocal_dep"\x1b\n\x03Dep\x12\x14\n\x05value\x18\x01 \x01(\tR\x05valueb\x06proto3',
    [],
    {
        "Dep": Dep,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `local_dep/dep.proto`."""
    return _DESC
